<?php
/** @var Skywalker_InternshipBlog_Block_Category $this */
?>
<?php
$categories = $this->getCategories();
?>
<h1>Post's categories</h1>
<div class="category-container">
    <ul class="category-list">
    <?php foreach ($categories as $category): ?>
        <li class="category-item"><a href="
            <?= Mage::getUrl(
                    '*/post/list',
                    [
                        'category'=> $category->getId()
                    ]);
            ?>
        " class="category-link"><h3><?= $category->getName(); ?></h3></a></li>
    <?php endforeach; ?>
    </ul>
</div>
