<?php
/** @var Skywalker_InternshipBlog_Block_Post_List $this */
?>
<?php
    $posts = $this->getPosts();
    $category = $this->getCategory();
    $imgUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'upload' . DS . $category->getImage();
?>
<h1><?= $category->getName(); ?> Category</h1>
<div class="description">
    <p><?= $category->getDescription(); ?></p>
    <?php if ($category->getImage()) : ?>
        <img src="<?= $imgUrl; ?>" width="200" height="200" alt="">
    <?php endif; ?>
</div>
<h2>Posts</h2>


<div class="post-container">
    <ul class="post-list">
        <?php $_odd = ''; ?>
        <?php foreach ($this->getCollection() as $post) : ?>
            <li class="post-item">
                <a href="
            <?= Mage::getUrl(
                    '*/*/show',
                    [
                        'id' => $post->getId()
                    ]);
                ?>
            ">
                    <div>
                        <h2><?= $post->getName(); ?></h2>
                        <p><?= $post->getShortDescription(); ?></p>
                    </div>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php echo $this->getPagerHtml(); ?>
</div>


