<?php
/** @var Skywalker_InternshipBlog_Block_Post_List $this */
?>
<?php
    $posts = $this->getPosts();
    $category = $this->getCategory();
?>
<h1><?= $category->getName(); ?> Category</h1>
<p><?= $category->getDescription(); ?> <img src="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'upload' . DS . $category->getImage(); ?>" width="200" height="200" alt=""></p>

<h2>Posts</h2>
<ul>
    <?php foreach ($posts as $post) : ?>
        <li><a href="
            <?= Mage::getUrl(
                    '*/*/show',
                    [
                        'id' => $post->getId()
                    ]);
            ?>
            "><?= $post->getShortDescription(); ?></a></li>
    <?php endforeach; ?>
</ul>

