<?php
/** @var Skywalker_Internship_Block_View $this */
?>
<?php
    $comments = $this->getComments();
?>

<ul>
    <?php foreach ($comments as $comment) : ?>
        <li>
            <div style="padding: 20px;">
                <p><?= $comment->getText(); ?></p>
                <p style="display: flex; justify-content: space-between;">
                    <span><?= $comment->getAuthor()->getName(); ?></span>
                    <time><?= $comment->getDate(); ?></time>
                </p>
            </div>
        </li>
    <?php endforeach; ?>
</ul>
<div class="<?= $this->getData('class'); ?>">
    <?php echo $this->getChildHtml('internship.map'); ?>
</div>
<div class="map">
    <?php echo $this->getChildHtml('google_map'); ?>
</div>

